# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yaPHwugOPXOWCD_dvV8Ru5Pp7CzCZB6m
"""

import streamlit as st
import joblib
import re
import string

# Load the saved model
pipeline = joblib.load('emotion_detection_model.pkl')

# Preprocessing
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# App UI
st.title("Emotion Detection from Text")

user_input = st.text_area("Enter your sentence here:")

if st.button("Predict Emotion"):
    if user_input.strip() == "":
        st.warning("Please enter some text to predict.")
    else:
        cleaned_input = clean_text(user_input)
        prediction = pipeline.predict([cleaned_input])[0]
        st.success(f"Predicted Emotion: {prediction}")

